name = "PolymerArchitecture"
uuid = "9f77f41a-3be8-4884-a3be-1fccfab54d3c"
authors = ["Yi-Xin Liu <lyx@fudan.edu.cn>"]
version = "0.1.0"

[deps]
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Polymer = "3c6f16a5-7773-4db2-b4fd-b1ef4c83c671"
TikzGraphs = "b4f28e30-c73f-5eaf-a395-8a9db949a742"
TikzPictures = "37f6aa50-8035-52d0-81c2-5a1d08754b2d"

[compat]
julia = "1.5"
LightGraphs = "1.3"
Polymer = ">= 0.5.0"
TikzGraphs = "1.1"
TikzPictures = "3.3"