name = "PolymerArchitecture"
uuid = "9f77f41a-3be8-4884-a3be-1fccfab54d3c"
authors = ["Yi-Xin Liu <lyx@fudan.edu.cn>"]
version = "0.1.0"

[deps]
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Polymer = "3c6f16a5-7773-4db2-b4fd-b1ef4c83c671"
TikzGraphs = "b4f28e30-c73f-5eaf-a395-8a9db949a742"
TikzPictures = "37f6aa50-8035-52d0-81c2-5a1d08754b2d"

[compat]
Graphs = "1.6"
Polymer = "0.8.2"
TikzGraphs = "1.3"
TikzPictures = "3.3, 3.4"
julia = "1.6"
