name = "PolymerArchitecture"
uuid = "9f77f41a-3be8-4884-a3be-1fccfab54d3c"
authors = ["Yi-Xin Liu <lyx@fudan.edu.cn>"]
version = "0.1.0"

[deps]
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"
Polymer = "3c6f16a5-7773-4db2-b4fd-b1ef4c83c671"
